name: EN | Bug report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, make sure you are running the latest build of Leaf and checked for duplicate issues in [Issues](https://github.com/Winds-Studio/Leaf/issues) and the [Leaf docs](https://www.leafmc.one/docs)!

  - type: checkboxes
    attributes:
      label: Checklist
      description: |
        Before you scroll down, select boxes below.
      options:
        - label: I have searched the existing issues and the documentation
          required: true
        - label: I ticked all the boxes without actually reading them
          required: false
        - label: I am using latest Leaf build from https://www.leafmc.one/download
          required: true
        - label: I tested and couldn't replicate this issue on latest [Paper](https://papermc.io/downloads/paper) or [Purpur](https://purpurmc.org/download/purpur) build
          required: true

  - type: textarea
    attributes:
      label: What behaviour is observed?
      description: A clear and concise description of what the behavior is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: A clear and concise description of what you expected to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce?
      description: Steps to reproduce this behaviour.
      placeholder: |
        1. Enter server ...
        2. Execute command /example ...
        3. Server crashes ...
        4. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Spark profiler link
      description: |
        Link of spark profiler, which including helpful information helps us to work with your issue,
        see https://spark.lucko.me/docs/ to learn how to use spark.
    validations:
      required: true

  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant errors or full log to either https://mclo.gs or https://pastes.dev, save and the paste the link in this box.
