name: EN | Feature request
description: Suggest an idea to improve Leaf
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request for Leaf! Please fill out the following form to help us make sure your feature request will actually improve Leaf!
  - type: textarea
    attributes:
      label: What feature do you want to see added?
      description: A clear and concise description of your feature request.
    validations:
      required: true
