name: CN | 问题反馈
description: 创建一个问题反馈来帮助我们进步！
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        在反馈问题之前, 请确保您正在使用最新版本的 Leaf, 并浏览 [Issues](https://github.com/Winds-Studio/Leaf/issues) 和 [Leaf 文档](https://www.leafmc.one/zh/docs), 检查你的问题是否已被汇报！

  - type: checkboxes
    attributes:
      label: 自我检查表
      description: |
        在浏览并填写其他选项之前, 请先勾选以下的框。
      options:
        - label: 我已经浏览过 Issues 和 Leaf 文档, 并确保汇报的不是已知问题
          required: true
        - label: 我勾选了所有框, 因为我根本就没仔细看他们是什么
          required: false
        - label: 我正在使用从 https://www.leafmc.one/zh/download 下载的最新 Leaf 构建
          required: true
        - label: 我无法在 最新 [Paper](https://papermc.io/downloads/paper) 或 [Purpur](https://purpurmc.org/download/purpur) 构建上复现此问题
          required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 清晰简洁地描述所观察到的行为。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 所期望的行为
      description: 清晰简洁地描述您预期发生的情况。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 如何复现？
      description: 简单描述复现此问题的步骤。
      placeholder: |
        1. 进入服务器 '...'
        2. 输入/example '...'
        3. 服务器崩溃 '...'
        4. 在控制台看到报错
    validations:
      required: true

  - type: input
    attributes:
      label: Spark profiler 链接
      description: |
        粘贴你的 Spark profiler 链接到此处, Spark profiler 往往包含了对解决此问题有用的信息, 
        查阅 https://spark.lucko.me/docs/ 来学习如何使用Spark。
    validations:
      required: true

  - type: input
    attributes:
      label: 错误日志 (如存在)
      description: 请上传完整的报错信息或完整日志到 https://mclo.gs 或 https://gist.github.com , 并将链接粘贴在此处。
